---
services:
  spectrespecs_app:
    container_name: 'spectrespecs'
    image: ghcr.io/umami-software/umami:mysql-latest
    environment:
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:3306/${DB_NAME}
      DATABASE_TYPE: mysql
      APP_SECRET: replace-me-with-a-random-string
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://spectrespecs.test/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      spectrespecs:
      nexus:
        aliases:
        - spectrespecs.test

networks:
  spectrespecs:
    name: nexus_spectrespecs
  nexus:
    name: nexus
    external: true
